// loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// onboarding
export const ONBOARDING_UPDATE = 'ONBOARDING_UPDATE';
export const CREATE_ATHLETE_AND_ACCOUNT = 'CREATE_ATHLETE_AND_ACCOUNT';
export const ACCOUNT_CREATION_FAILED = 'ACCOUNT_CREATION_FAILED';
export const ONBOARDING_CLEAR_ERROR = 'ONBOARDING_CLEAR_ERROR';

// user
export const USER_UPDATE = 'USER_UPDATE';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// banking
export const UPDATE_HOME_STEP = 'UPDATE_HOME_STEP';
export const UPDATE_POD_SETTINGS = 'UPDATE_POD_SETTINGS';
export const POD_SETTINGS_UPDATED = 'POD_SETTINGS_UPDATED';
export const GET_RECENT_TRANSACTIONS = 'GET_RECENT_TRANSACTIONS';
export const RECENT_TRANSACTIONS_LOADED = 'RECENT_TRANSACTIONS_LOADED';
export const MARK_RECENT_TRANSACTION_READ = 'MARK_RECENT_TRANSACTION_READ';
